// packages/angular-virtual/src/index.ts
import {
  AfterRenderPhase,
  DestroyRef,
  afterNextRender,
  computed,
  effect,
  inject,
  signal,
  untracked,
} from '@angular/core'
import {
  Virtualizer,
  elementScroll,
  observeElementOffset,
  observeElementRect,
  observeWindowOffset,
  observeWindowRect,
  windowScroll,
} from '@tanstack/virtual-core'
import { proxyVirtualizer } from './proxy'
import type { ElementRef, Signal } from '@angular/core'
import type {
  PartialKeys,
  VirtualKey,
  VirtualizerOptions,
} from '@tanstack/virtual-core'
import type { AngularVirtualizer } from './types'

export * from '@tanstack/virtual-core'
export * from './types'

function createVirtualizerBase<
  TScrollElement extends Element | Window,
  TItemElement extends Element,
  TKey extends VirtualKey,
>(
  options: Signal<VirtualizerOptions<TScrollElement, TItemElement, TKey>>,
): AngularVirtualizer<TScrollElement, TItemElement, TKey> {
  let virtualizer: Virtualizer<TScrollElement, TItemElement, TKey>
  function lazyInit() {
    virtualizer ??= new Virtualizer(options())
    return virtualizer
  }

  const virtualizerSignal = signal(virtualizer!, { equal: () => false })

  // two-way sync options
  effect(
    () => {
      const _options = options()
      lazyInit()
      virtualizerSignal.set(virtualizer)
      virtualizer.setOptions({
        ..._options,
        onChange: (instance, sync) => {
          // update virtualizerSignal so that dependent computeds recompute.
          virtualizerSignal.set(instance)
          _options.onChange?.(instance, sync)
        },
      })
      // update virtualizerSignal so that dependent computeds recompute.
      virtualizerSignal.set(virtualizer)
    },
    { allowSignalWrites: true },
  )

  const scrollElement = computed(() => options().getScrollElement())
  // let the virtualizer know when the scroll element is changed
  effect(
    () => {
      const el = scrollElement()
      if (el) {
        untracked(virtualizerSignal)._willUpdate()
      }
    },
    { allowSignalWrites: true },
  )

  let cleanup: () => void | undefined
  afterNextRender(() => (virtualizer ?? lazyInit())._didMount(), {
    phase: AfterRenderPhase.Read,
  })

  inject(DestroyRef).onDestroy(() => cleanup?.())

  return proxyVirtualizer(virtualizerSignal, lazyInit)
}

export function injectVirtualizer<
  TScrollElement extends Element,
  TItemElement extends Element,
  TKey extends VirtualKey,
>(
  options: () => PartialKeys<
    Omit<
      VirtualizerOptions<TScrollElement, TItemElement, TKey>,
      'getScrollElement'
    >,
    'observeElementRect' | 'observeElementOffset' | 'scrollToFn'
  > & {
    scrollElement: ElementRef<TScrollElement> | TScrollElement | undefined
  },
): AngularVirtualizer<TScrollElement, TItemElement, TKey> {
  const resolvedOptions = computed(() => {
    return {
      observeElementRect: observeElementRect,
      observeElementOffset: observeElementOffset,
      scrollToFn: elementScroll,
      getScrollElement: () => {
        const elementOrRef = options().scrollElement
        return (
          (isElementRef(elementOrRef)
            ? elementOrRef.nativeElement
            : elementOrRef) ?? null
        )
      },
      ...options(),
    }
  })
  return createVirtualizerBase<TScrollElement, TItemElement, TKey>(
    resolvedOptions,
  )
}

function isElementRef<T extends Element>(
  elementOrRef: ElementRef<T> | T | undefined,
): elementOrRef is ElementRef<T> {
  return elementOrRef != null && 'nativeElement' in elementOrRef
}

export function injectWindowVirtualizer<
  TItemElement extends Element,
  TKey extends VirtualKey,
>(
  options: () => PartialKeys<
    VirtualizerOptions<Window, TItemElement, TKey>,
    | 'getScrollElement'
    | 'observeElementRect'
    | 'observeElementOffset'
    | 'scrollToFn'
  >,
): AngularVirtualizer<Window, TItemElement, TKey> {
  const resolvedOptions = computed(() => {
    return {
      getScrollElement: () => (typeof document !== 'undefined' ? window : null),
      observeElementRect: observeWindowRect,
      observeElementOffset: observeWindowOffset,
      scrollToFn: windowScroll,
      initialOffset: () =>
        typeof document !== 'undefined' ? window.scrollY : 0,
      ...options(),
    }
  })
  return createVirtualizerBase<Window, TItemElement, TKey>(resolvedOptions)
}

// packages/react-virtual/src/index.tsx
import * as React from 'react'
import { flushSync } from 'react-dom'
import {
  Virtualizer,
  elementScroll,
  observeElementOffset,
  observeElementRect,
  observeWindowOffset,
  observeWindowRect,
  windowScroll,
} from '@tanstack/virtual-core'
import type {
  PartialKeys,
  VirtualKey,
  VirtualizerOptions,
} from '@tanstack/virtual-core'

export * from '@tanstack/virtual-core'

const useIsomorphicLayoutEffect =
  typeof document !== 'undefined' ? React.useLayoutEffect : React.useEffect

function useVirtualizerBase<
  TScrollElement extends Element | Window,
  TItemElement extends Element,
  TKey extends VirtualKey,
>(
  options: VirtualizerOptions<TScrollElement, TItemElement, TKey>,
): Virtualizer<TScrollElement, TItemElement, TKey> {
  const rerender = React.useReducer(() => ({}), {})[1]

  const resolvedOptions: VirtualizerOptions<
    TScrollElement,
    TItemElement,
    TKey
  > = {
    ...options,
    onChange: (instance, sync) => {
      if (sync) {
        flushSync(rerender)
      } else {
        rerender()
      }
      options.onChange?.(instance, sync)
    },
  }

  const [instance] = React.useState(
    () => new Virtualizer<TScrollElement, TItemElement, TKey>(resolvedOptions),
  )

  instance.setOptions(resolvedOptions)

  useIsomorphicLayoutEffect(() => {
    return instance._didMount()
  }, [])

  useIsomorphicLayoutEffect(() => {
    return instance._willUpdate()
  })

  return instance
}

export function useVirtualizer<
  TScrollElement extends Element,
  TItemElement extends Element,
  TKey extends VirtualKey,
>(
  options: PartialKeys<
    VirtualizerOptions<TScrollElement, TItemElement, TKey>,
    'observeElementRect' | 'observeElementOffset' | 'scrollToFn'
  >,
): Virtualizer<TScrollElement, TItemElement, TKey> {
  return useVirtualizerBase<TScrollElement, TItemElement, TKey>({
    observeElementRect: observeElementRect,
    observeElementOffset: observeElementOffset,
    scrollToFn: elementScroll,
    ...options,
  })
}

export function useWindowVirtualizer<
  TItemElement extends Element,
  TKey extends VirtualKey,
>(
  options: PartialKeys<
    VirtualizerOptions<Window, TItemElement, TKey>,
    | 'getScrollElement'
    | 'observeElementRect'
    | 'observeElementOffset'
    | 'scrollToFn'
  >,
): Virtualizer<Window, TItemElement, TKey> {
  return useVirtualizerBase<Window, TItemElement, TKey>({
    getScrollElement: () => (typeof document !== 'undefined' ? window : null),
    observeElementRect: observeWindowRect,
    observeElementOffset: observeWindowOffset,
    scrollToFn: windowScroll,
    initialOffset: () => (typeof document !== 'undefined' ? window.scrollY : 0),
    ...options,
  })
}
